prefix                          = "dev"
google_project                  = "genuine-box-424516-p1"
delegate_from                   = ["serviceAccount:terraform-sa@genuine-box-424516-p1.iam.gserviceaccount.com"]
databricks_account_id           = "3889e6a7-4f3a-4ab7-8970-a8686fbb2396"
workspace_name                  = "Develop"
workspace_admin_privileges      = ["jovmilan995@gmail.com"]
google_region                   = "us-central1"
google_zone                     = "us-central1-a"
cluster_name                    = "Develop Cluster"
cluster_autotermination_minutes = 10
cluster_num_workers             = 1
email_notifications_on_failure  = ["jovmilan995@gmail.com"]
email_notifications_on_success  = ["jovmilan995@gmail.com"]