---
# This is a basic GitHub Actions pipeline to validate Terraform
name: Databricks Terraform Infrastructure Pipeline
on:
  push:
    branches: [main, dev, stg]
  pull_request:
    branches: [main]
env:
  TERRAFORM_VERSION: 1.7.5

jobs:
  dev:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/deploy_environment.yml
    with:
      environment: dev
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
    secrets: inherit