name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash
    working-directory: "./terraform/environments/${{ inputs.environment }}"


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DSKLSD
        run: ls -alh
      
