name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run: 
        working-directory: terraform/environments/${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: kdls
        run: pwd
      
