---
name: Terraform Workflow
on:
  push:
    branches: [main, dev, stg]
  pull_request:
    branches: [main, dev, stg]
# variables:
#   TERRAFORM_VERSION: 1.8.4
#   TERRAFORM_BACKEND_NAME: "databricks-alex-tfstate1"

jobs:
  dev:
    if: github.ref == 'refs/heads/dev' || (github.base_ref == 'dev' && github.event_name == 'pull_request')
    uses: ./.github/workflows/terraform-pr-check-and-provision.yml
    with:
      environment: dev
      terraform_version: "1.8.4"
      terraform_backend_name: "databricks-alex-tfstate1"
    secrets: inherit

  stg:
    if: github.ref == 'refs/heads/stg' || (github.base_ref == 'stg' && github.event_name == 'pull_request')
    uses: ./.github/workflows/terraform-pr-check-and-provision.yml
    with:
      environment: stg
      terraform_version: "1.8.4"
      terraform_backend_name: "databricks-alex-tfstate1"
    secrets: inherit

  prod:
    if: github.ref == 'refs/heads/main' || (github.base_ref == 'main' && github.event_name == 'pull_request')
    uses: ./.github/workflows/terraform-pr-check-and-provision.yml
    with:
      environment: prod
      terraform_version: "1.8.4"
      terraform_backend_name: "databricks-alex-tfstate1"
    secrets: inherit
